### ISSUE TITLE
Empty questions

### ISSUE THREAD

**Issue by krios2146** [enhorse/java-interview#107]
Если вы хотите переопределить `equals()`, какие условия должны выполняться? (пустой)
(https://github.com/enhorse/java-interview/blob/master/core.md#%D0%B5%D1%81%D0%BB%D0%B8-%D0%B2%D1%8B-%D1%85%D0%BE%D1%82%D0%B8%D1%82%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C-equals-%D0%BA%D0%B0%D0%BA%D0%B8%D0%B5-%D1%83%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F)
Тоже самое что и -
Правила переопределения метода `Object.equals()`.
https://github.com/enhorse/java-interview/blob/master/core.md#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0-objectequals

Какая связь между `hashCode()` и `equals()`? 
https://github.com/enhorse/java-interview/blob/master/core.md#%D0%BA%D0%B0%D0%BA%D0%B0%D1%8F-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-hashcode-%D0%B8-equals

**Comment by enhorse** [comment]
Эти вопросы подразумевают под собой одинаковые ответы
