### ISSUE TITLE
Lexical mistakes

### ISSUE THREAD

**Issue by nickrogracher** [enhorse/java-interview#15]
Есть пару лексических ошибок:
![image](https://user-images.githubusercontent.com/48067169/73738547-b6a0b880-4755-11ea-8684-16f29bf87d24.png)
и
![image](https://user-images.githubusercontent.com/48067169/73738683-f798cd00-4755-11ea-81c4-c68c286a36c0.png)

Я исправил у себя локально это. Могу ли я запушить эти изменения?

**Comment by enhorse** [comment]
Привет!
Да, конечно, через Pull-Request.

Спасибо!

**Comment by nickrogracher** [comment]
Выдает 403 ошибку при попытке пуша:
![image](https://user-images.githubusercontent.com/48067169/73739533-76423a00-4757-11ea-8821-14b1593e67e8.png)

**Comment by enhorse** [comment]
Push это не совсем PullRequest.

Вот нагуглилась какая-то инструкция, бегло посмотрел, вроде то, что надо
https://github.com/urfu-2015/guides/blob/master/how-to-pull-request.md

**Comment by nickrogracher** [comment]
Спасибо, понял=)

**Comment by nickrogracher** [comment]
Слушай, а можешь добавить SOLID в CORE?

**Comment by Narryel** [comment]
> Слушай, а можешь добавить SOLID в CORE?

а можно тут чатик не устраивать, всем подписанным же оповещения приходят :)

**Comment by enhorse** [comment]
> Слушай, а можешь добавить SOLID в CORE?

Не совсем понял вопроса, но если что-то нужно куда-то добавить, - то нужен PR и если он заслуживает добавления, то он, конечно же, окажется в master.
