### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by fastchatter** [enhorse/java-interview#19]
https://github.com/enhorse/java-interview/blob/master/jcf.md#%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B8%D1%82%D0%B5-iterator-%D0%B8-listiterator
> При помощи ListIterator вы можете модифицировать список, добавляя/удаляя элементы с помощью методов add() и remove(). Iterator не поддерживает данного функционала.

на самом деле
https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#remove--

**Comment by enhorse** [comment]
Тут речь, о том что для сферического `Iterator`:
```java
    default void remove() {
        throw new UnsupportedOperationException("remove");
    }
```
а, `add()` и вовсе отсутствует.
