### ISSUE TITLE
Local classes - incorrect info

### ISSUE THREAD

**Issue by alebabai** [enhorse/java-interview#26]
## what
https://github.com/enhorse/java-interview/blob/master/core.md#%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%81-%D0%BA%D0%B0%D0%BA%D0%BE%D0%B2%D1%8B-%D0%B5%D0%B3%D0%BE-%D0%BE%D1%81%D0%BE%D0%B1%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8

Не могут иметь внутри себя статических объявлений (полей, методов, классов);

## why

Поля всё-таки могут иметь статические

![image](https://user-images.githubusercontent.com/19958900/75786467-67f73600-5d76-11ea-8644-15207edacbd1.png)

**Comment by kortov** [comment]
И правда, хотя не пойму как про это в спеке найти (не нашел). Вот тока есть [Local Classes в самом низу](https://docs.oracle.com/javase/tutorial/java/javaOO/localclasses.html)  

> A local class can have static members provided that they are constant variables. (A constant variable is a variable of primitive type or type String that is declared final and initialized with a compile-time constant expression. A compile-time constant expression is typically a string or an arithmetic expression that can be evaluated at compile time.

**Comment by enhorse** [comment]
@alebabai Сможете оформить в виде Pull Request?

**Comment by alebabai** [comment]
> @alebabai Сможете оформить в виде Pull Request?

да, конечно
