### ISSUE TITLE
Худшее время добавление в LinkedList скорее (N/2)

### ISSUE THREAD

**Issue by IvanAgafonov** [enhorse/java-interview#69]
Худшее время добавление в LinkedList скорее (N/2) так как для вставки по индексу как и для удаления, может быть выбран как хвост, так и голова списка, тогда получится что максимум надо перейти по половине списка.

https://github.com/enhorse/java-interview/blob/master/jcf.md#%D0%BA%D0%B0%D0%BA%D0%BE%D0%B5-%D1%85%D1%83%D0%B4%D1%88%D0%B5%D0%B5-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0-add-%D0%B4%D0%BB%D1%8F-linkedlist

**Comment by Kikk3r** [comment]
O(N/2) = O(N)
