### ISSUE TITLE
Ошибка в вопросе  "в чём разница между «конкуренцией» и «параллелизмом»?"

### ISSUE THREAD

**Issue by showtime25st** [enhorse/java-interview#91]
Добрый день! У вас тут ошибка: "если поток управления один, то конкурентного выполнения быть не может"  https://en.wikipedia.org/wiki/Concurrency_(computer_science) и выдержка из этой статьи: "Concurrency is about structure, parallelism is about execution, concurrency provides a way to structure a solution to solve a problem that may (but not necessarily) be parallelizable.[3]." Из этого следует, что конкурентное выполнение может быть на одном процессоре. И вот еще на русском статья https://www.zhashkevych.com/concurrency-and-parallelism.

**Comment by isalig** [comment]
Так тут речь о потоках, а не о процессорах. Конкуретность про то и есть, что один процессор "разрывается" между задачами, делая то одно, то другое
